all: 
	make clean 
	make model

clean:
	!Rm *.o
	!Rm model

model: tstModel.o model.o events.o
	cc68x tstModel.o model.o events.o -o model

tstModel.o: tstModel.c events.h 
	cc68x -g -c tstModel.c

model.o: model.c model.h 
	cc68x -g -c model.c
	
events.o: events.c events.h 
	cc68x -g -c events.c
	